services:
  messy:
    container_name: messy
    build:
      context: .
      dockerfile: .docker/aspnet/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - postgres
    networks:
      - backend
      
  postgres:
    container_name: "postgresql"
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
    networks:
      - backend 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initscripts:/docker-entrypoint-initdb.d
          
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .docker/nginx:/etc/nginx/conf.d
    depends_on:
      - messy
    ports:
      - "8000:80"
    networks:
      - backend
        
networks:
  backend:
      driver: bridge
      
volumes:
  postgres_data: